### PR TITLE
Add support for Bancor prices.

### PR DESCRIPTION
**Pull request by uivlis**
Note: Obviously, I didn't test this. I did work with the Bancor converter in the past, but since you don't seem to have a test environment, I think it's best to wait until you set up that, and maybe you'll have a future bounty on it!

### CODE REVIEW

**Review by mikedeshazer — COMMENTED** [review]
This could be tested in remix for syntax errors though... for example:
 "reutrn price;" in draftpremium.sol breaks code, etc

**Comment by mikedeshazer** [comment]
I left the comment "This could be tested in remix for syntax errors though... for example:
"reutrn price;" in draftpremium.sol breaks code, etc"
But also regarding testing, this could be tested on mainnet. Just share your ETh address, I'll send you over some ETH to deploy the contract to test.

**Comment by uivlis** [comment]
Thank you @mikedeshazer, I should have thought at that one. Check it out now, it should compile (there are some warnings from the already existing code).
Regarding testing... I still think you need a more or less proper testing environment. Just publishing to mainnet is not exactly the way to go, in my humble opinion. First, I wouldn't want to spend purposelessly through your ether. And second, is there not a version of this contract already deployed? Because, if it is, then that version will need to be updated by the owner (which is not me). And if it isn't, then I guess this reaches over the purpose of this bounty.

**Comment by mikedeshazer** [comment]
@uivlis you make a good point; however, because it's DeFi it relies on about 30 or so other contracts on mainnet, that are moving targets... for example DAI just changed to SAI and has different addresses. Kyber and Uniswap are updating at any moment etc. And the contract is for people who will mostly doing arb across these exchanges with real funds. With the Defi testnet apps of the exchanges, they mostly dont work etc, so that's currently the justification... but completely undertsand. I will however work on getting tests written that can verify contracts on mainnet.

**Comment by uivlis** [comment]
Hi @mikedeshazer maybe [this](https://github.com/ProofSuite/OrFeedSmartContracts/pull/11) would solve it?

**Pull request closed without merging**
