### PR TITLE
Update multiexchangewithbancordraft.sol

### PR DESCRIPTION
**Pull request by uivlis**
Hi @mikedeshazer I think it should work now.

### CODE REVIEW

**Comment by mikedeshazer** [comment]
@uivlis tested your code. Here's the contract on mainnet: https://etherscan.io/dapp/0x76e5f4ebd8916d72bc16ef60782da0a4bf72df64#readContract
I tried calling the getExchangeRate function with DAI,SAI,ETH,BTC etc with param "BUY-BANCOR-EXCHANGE" and "SELL-BANCOR-EXCHANGE" as venue, but all return 0.
Which tokens/paths did you test directly to Bancor? Perhaps that might hint us towards solving the elusive pathing problem.

**Comment by mikedeshazer** [comment]
@uivlis found this which might be useful: https://github.com/bancorprotocol/contracts/issues/282

**Comment by uivlis** [comment]
Hi @mikedeshazer I updated the `BancorNetwork` contract to the one deployed at the address from the issue you mentioned.

**Comment by k06a** [comment]
@uivlis @mikedeshazer 👍

**Comment by k06a** [comment]
Read this thread, I fixed more problems with converters: https://github.com/bancorprotocol/contracts/pull/281

I believe the latest working version is this one: https://etherscan.io/address/0x7a9b986420d734bb3fe98439a2d945ab97757595#contracts

**Comment by uivlis** [comment]
Thanks! I updated the contract to that address in the latest commit. @k06a Just to be sure, is this the right way to build the path for `getReturnByPath`:
```
// token1ToBancor address
path[0] = IERC20Token(token1ToBancor);
// BNT converter
path[1] = IERC20Token(bancorConverterRegistry.latestConverterAddress(0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c));
// BNT address
path[2] = IERC20Token(0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c);
// token2ToBancor converter
path[3] = IERC20Token(bancorConverterRegistry.latestConverterAddress(token2ToBancor));
// token2ToBancor address
path[4] = IERC20Token(token2ToBancor);
(price, ) = bancorNetwork.getReturnByPath(path, amount);
```
for, say, `amount` of `token1ToBancor` to `token2ToBancor`?

**Comment by k06a** [comment]
@uivlis, yep `TKN1,CNV1,BNT,CNV2,TKN2` is true for token-to-token. Handle ETH and BNT as source and destination, path could contain 3 instead of 5 items.

**Comment by mikedeshazer** [comment]
Will test it out in the AM.We are working on a better testing workflow but will now do it manually and update soon

**Comment by k06a** [comment]
Check this comment: https://github.com/bancorprotocol/contracts/issues/282#issuecomment-562046437

**Comment by mikedeshazer** [comment]
@uivlis deployed your solution here: https://etherscan.io/address/0x253b6f3e72d504f550ff04fec1d467d9459cd8cb#readContract
From the recent pull request. Still does not seem to work
Perhaps @k06a comment share will help 
I can certainly say, once this problem is solved, will probably save alot of people headaches.

**Pull request merged**
